// This file was autogenerated by gulp-closure-deps plugin.
// Please do not edit.
goog.addDependency('../../../../src/complexnumber.js', ['ComplexNumber'], [], false);
goog.addDependency('../../../../src/mandelbrot.js', ['app'], ['ComplexNumber'], false);