// This file was autogenerated by gulp-closure-deps plugin.
// Please do not edit.
goog.addDependency('../../../../bower_components/animate/src/animate/animate.js', ['animate'], ['animate.Conductor'], false);
goog.addDependency('../../../../bower_components/animate/src/animate/animation.js', ['animate.Animation'], ['animate.AnimationState'], false);
goog.addDependency('../../../../bower_components/animate/src/animate/animationstate.js', ['animate.AnimationState'], [], false);
goog.addDependency('../../../../bower_components/animate/src/animate/conductor.js', ['animate.Conductor'], ['animate.Animation'], false);
goog.addDependency('../../../../bower_components/animate/src/animate/fps.js', ['animate.Fps', 'animate.Fps.View'], ['animate.Animation'], false);
goog.addDependency('../../../../src/js/app.js', ['app'], ['ComplexNumber', 'animate', 'animate.Animation', 'animate.Fps', 'geom', 'goog.Uri', 'mandelbrot.Canvas2dView', 'mandelbrot.Field', 'mandelbrot.WebglView', 'util'], false);
goog.addDependency('../../../../src/js/complexnumber.js', ['ComplexNumber'], [], false);
goog.addDependency('../../../../src/js/geom.js', ['geom'], [], false);
goog.addDependency('../../../../src/js/mandelbrot/canvas2dview.js', ['mandelbrot.Canvas2dView'], ['mandelbrot.Cutout'], false);
goog.addDependency('../../../../src/js/mandelbrot/cutout.js', ['mandelbrot.Cutout'], ['ComplexNumber'], false);
goog.addDependency('../../../../src/js/mandelbrot/field.js', ['mandelbrot.Field'], ['ComplexNumber'], false);
goog.addDependency('../../../../src/js/mandelbrot/webgl.js', ['webgl'], ['goog.Promise', 'goog.net.XhrIo'], false);
goog.addDependency('../../../../src/js/mandelbrot/webglview.js', ['mandelbrot.WebglView'], ['goog.Promise', 'goog.log', 'webgl'], false);
goog.addDependency('../../../../src/js/util.js', ['util'], [], false);